version: '2.2'

services:

  your_service:
    # Please add your service here and serve it on port 5000.
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - ASPNETCORE_HTTP_PORT=https://+:5001
      - ASPNETCORE_URLS=http://+:5000
    ports:
     - "5000:5000/tcp"
     - "5001:5001/tcp"
    mem_limit: 512m
    mem_reservation: 512m
    depends_on:
      - jaeger
      - httpbin

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "14268:14268/tcp"
      - "14250:14250/tcp"
      - "16686:16686"

  httpbin:
    image: kennethreitz/httpbin
    ports:
      - "8000:80"
